// -----------------------------------------------------------------------------
// Author: Cedric Hölzl
//
// Description:
//   SystemC wrapper for the Verilated SV top_crossbar (Verilator --sc output).
//   Mirrors the port convention of the native rtl/systemc/top_crossbar.hpp so
//   that the unified top.hpp wrapper can select this SV backend with
//   IMPL=top_crossbar.
//
//   Each flat read/write port group is driven by one RAGU/WAGU trace driver.
//   The port-group mapping (established in top.hpp and tb_top.cpp) is:
//     read : ports 0-3 → RAGU_A, ports 4-5 → RAGU_B, port 6 → RAGU_C,
//            port 7 → RAGU_D, port 8 → RAGU_E
//     write: ports 0-3 → WAGU_A, ports 4-5 → WAGU_B, port 6 → WAGU_D,
//            port 7 → WAGU_E
//   In the TDM backend the RAGU drivers feed per-group buffers; the TDM
//   arbiter and slot-allocation logic sit between those buffers and the
//   crossbar/bank backend. In the crossbar backend the mapping is direct.
//
//   The Verilated module (Vtop_crossbar, generated from top_crossbar.sv) exposes
//   packed OBI request/response arrays as flat wide bit vectors:
//     rport_req_i  : sc_in <sc_bv<NUM_RPORT * SV_NUM_REQ * OBI_REQ_W>>
//     rport_resp_o : sc_out<sc_bv<NUM_RPORT * SV_NUM_REQ * OBI_RESP_W>>
//     wport_req_i  : sc_in <sc_bv<NUM_WPORT * SV_NUM_REQ * OBI_REQ_W>>
//     wport_resp_o : sc_out<sc_bv<NUM_WPORT * SV_NUM_REQ * OBI_RESP_W>>
//
//   OBI struct field layout (SystemVerilog packed, LSB = field declared last):
//     obi_req_t (OBI_REQ_W bits per manager):
//       [OBI_DW-1        :  0       ] wdata
//       [OBI_DW+31       :  OBI_DW  ] addr
//       [OBI_DW+32+BEW-1 :  OBI_DW+32] be
//       [OBI_DW+32+BEW   ]            we
//       [OBI_DW+32+BEW+1 ]            req
//     obi_resp_t (OBI_RESP_W bits per manager):
//       [OBI_DW-1 :  0      ] rdata
//       [OBI_DW   ]           rvalid
//       [OBI_DW+1 ]           gnt
//
//   OBI_DATA_WIDTH must be passed consistently via PARAMS= so that Verilator
//   receives -G and C++ receives -D with the same value. The port arrays use
//   uint64_t, so OBI_DATA_WIDTH > 64 silently truncates data in this wrapper.
//
// Template parameters:
//   NUM_RPORT, NUM_WPORT - read/write port counts
//   NUM_REQ              - OBI buses per external read/write port
//   SV_NUM_REQ           - NUM_REQ compiled into top_crossbar.sv packed ports
// -----------------------------------------------------------------------------

#ifndef TOP_CROSSBAR_SV_HPP
#define TOP_CROSSBAR_SV_HPP

#include <systemc.h>

#include <cstdint>

#include "Vtop_crossbar.h" // generated by Verilator --sc

#ifndef OBI_DATA_WIDTH
#define OBI_DATA_WIDTH 128
#endif

template <int NUM_RPORT = 2, int NUM_WPORT = 2, int NUM_REQ = 4, int NUM_BANK = 8,
          int NUM_ROW = 1024, int BYTES_PER_WORD = 4, int WORDS_PER_ROW = 4,
          int SV_NUM_REQ = NUM_REQ>
SC_MODULE(top_crossbar_sv) {
    static constexpr int NUM_RPORT_BUSES = NUM_RPORT * NUM_REQ;
    static constexpr int NUM_WPORT_BUSES = NUM_WPORT * NUM_REQ;
    static constexpr int SV_RPORT_BUSES  = NUM_RPORT * SV_NUM_REQ;
    static constexpr int SV_WPORT_BUSES  = NUM_WPORT * SV_NUM_REQ;

    static_assert(NUM_REQ <= SV_NUM_REQ,
                  "external NUM_REQ cannot exceed the SV top_crossbar NUM_REQ");

    static constexpr int OBI_DW     = OBI_DATA_WIDTH;
    static constexpr int OBI_BEW    = OBI_DW / 8;
    static constexpr int OBI_REQ_W  = OBI_DW + 32 + OBI_BEW + 2;
    static constexpr int OBI_RESP_W = OBI_DW + 2;

    sc_in<bool> clk_i;
    sc_in<bool> rst_ni;

    sc_in<bool>      rport_req_i[NUM_RPORT_BUSES];
    sc_in<uint64_t>  rport_addr_i[NUM_RPORT_BUSES];
    sc_in<bool>      rport_we_i[NUM_RPORT_BUSES];
    sc_in<uint32_t>  rport_be_i[NUM_RPORT_BUSES];
    sc_in<uint64_t>  rport_wdata_i[NUM_RPORT_BUSES];
    sc_out<bool>     rport_gnt_o[NUM_RPORT_BUSES];
    sc_out<bool>     rport_rvalid_o[NUM_RPORT_BUSES];
    sc_out<uint64_t> rport_rdata_o[NUM_RPORT_BUSES];

    sc_in<bool>      wport_req_i[NUM_WPORT_BUSES];
    sc_in<uint64_t>  wport_addr_i[NUM_WPORT_BUSES];
    sc_in<bool>      wport_we_i[NUM_WPORT_BUSES];
    sc_in<uint32_t>  wport_be_i[NUM_WPORT_BUSES];
    sc_in<uint64_t>  wport_wdata_i[NUM_WPORT_BUSES];
    sc_out<bool>     wport_gnt_o[NUM_WPORT_BUSES];
    sc_out<bool>     wport_rvalid_o[NUM_WPORT_BUSES];
    sc_out<uint64_t> wport_rdata_o[NUM_WPORT_BUSES];

    Vtop_crossbar vdut;

    sc_signal<sc_bv<SV_RPORT_BUSES * OBI_REQ_W>>  s_rport_req;
    sc_signal<sc_bv<SV_RPORT_BUSES * OBI_RESP_W>> s_rport_resp;
    sc_signal<sc_bv<SV_WPORT_BUSES * OBI_REQ_W>>  s_wport_req;
    sc_signal<sc_bv<SV_WPORT_BUSES * OBI_RESP_W>> s_wport_resp;

    template <int REQ_W>
    static void pack_slot(sc_bv<REQ_W> & slot, bool req, uint64_t addr, bool we, uint32_t be,
                          uint64_t wdata) {
        slot.range(OBI_DW - 1, 0)                          = wdata;
        slot.range(OBI_DW + 32 - 1, OBI_DW)                = addr;
        slot.range(OBI_DW + 32 + OBI_BEW - 1, OBI_DW + 32) = be;
        slot[OBI_DW + 32 + OBI_BEW]                        = we ? 1 : 0;
        slot[OBI_DW + 32 + OBI_BEW + 1]                    = req ? 1 : 0;
    }

    void pack_rport_inputs() {
        sc_bv<SV_RPORT_BUSES * OBI_REQ_W> packed = 0;
        for (int port = 0; port < NUM_RPORT; ++port) {
            for (int lane = 0; lane < NUM_REQ; ++lane) {
                const int        ext  = port * NUM_REQ + lane;
                const int        slot = port * SV_NUM_REQ + lane;
                sc_bv<OBI_REQ_W> req_slot;
                pack_slot<OBI_REQ_W>(req_slot, rport_req_i[ext].read(), rport_addr_i[ext].read(),
                                     rport_we_i[ext].read(), rport_be_i[ext].read(),
                                     rport_wdata_i[ext].read());
                packed.range((slot + 1) * OBI_REQ_W - 1, slot * OBI_REQ_W) = req_slot;
            }
        }
        s_rport_req.write(packed);
    }

    void pack_wport_inputs() {
        sc_bv<SV_WPORT_BUSES * OBI_REQ_W> packed = 0;
        for (int port = 0; port < NUM_WPORT; ++port) {
            for (int lane = 0; lane < NUM_REQ; ++lane) {
                const int        ext  = port * NUM_REQ + lane;
                const int        slot = port * SV_NUM_REQ + lane;
                sc_bv<OBI_REQ_W> req_slot;
                pack_slot<OBI_REQ_W>(req_slot, wport_req_i[ext].read(), wport_addr_i[ext].read(),
                                     wport_we_i[ext].read(), wport_be_i[ext].read(),
                                     wport_wdata_i[ext].read());
                packed.range((slot + 1) * OBI_REQ_W - 1, slot * OBI_REQ_W) = req_slot;
            }
        }
        s_wport_req.write(packed);
    }

    void unpack_rport_outputs() {
        const sc_bv<SV_RPORT_BUSES * OBI_RESP_W> packed = s_rport_resp.read();
        for (int port = 0; port < NUM_RPORT; ++port) {
            for (int lane = 0; lane < NUM_REQ; ++lane) {
                const int ext  = port * NUM_REQ + lane;
                const int slot = port * SV_NUM_REQ + lane;
                const int base = slot * OBI_RESP_W;
                rport_rdata_o[ext].write(packed.range(base + OBI_DW - 1, base).to_uint64());
                rport_rvalid_o[ext].write(packed[base + OBI_DW].to_bool());
                rport_gnt_o[ext].write(packed[base + OBI_DW + 1].to_bool());
            }
        }
    }

    void unpack_wport_outputs() {
        const sc_bv<SV_WPORT_BUSES * OBI_RESP_W> packed = s_wport_resp.read();
        for (int port = 0; port < NUM_WPORT; ++port) {
            for (int lane = 0; lane < NUM_REQ; ++lane) {
                const int ext  = port * NUM_REQ + lane;
                const int slot = port * SV_NUM_REQ + lane;
                const int base = slot * OBI_RESP_W;
                wport_rdata_o[ext].write(packed.range(base + OBI_DW - 1, base).to_uint64());
                wport_rvalid_o[ext].write(packed[base + OBI_DW].to_bool());
                wport_gnt_o[ext].write(packed[base + OBI_DW + 1].to_bool());
            }
        }
    }

    SC_CTOR(top_crossbar_sv) : vdut("vdut") {
        vdut.clk_i(clk_i);
        vdut.rst_ni(rst_ni);
        vdut.rport_req_i(s_rport_req);
        vdut.rport_resp_o(s_rport_resp);
        vdut.wport_req_i(s_wport_req);
        vdut.wport_resp_o(s_wport_resp);

        SC_METHOD(pack_rport_inputs);
        for (int i = 0; i < NUM_RPORT_BUSES; ++i)
            sensitive << rport_req_i[i] << rport_addr_i[i] << rport_we_i[i] << rport_be_i[i]
                      << rport_wdata_i[i];

        SC_METHOD(unpack_rport_outputs);
        sensitive << s_rport_resp;

        SC_METHOD(pack_wport_inputs);
        for (int i = 0; i < NUM_WPORT_BUSES; ++i)
            sensitive << wport_req_i[i] << wport_addr_i[i] << wport_we_i[i] << wport_be_i[i]
                      << wport_wdata_i[i];

        SC_METHOD(unpack_wport_outputs);
        sensitive << s_wport_resp;
    }
};

#endif // TOP_CROSSBAR_SV_HPP
