// -----------------------------------------------------------------------------
// Author: Cedric Hölzl
//
// Description:
//   SystemC wrapper for the Verilated SV top_crossbar (Verilator --sc output).
//   Mirrors the port convention of the native rtl/systemc/top_crossbar.hpp so
//   that tb_top_crossbar.cpp can swap between the two DUTs by changing a single
//   #include and the class name.
//
//   The Verilated module (Vtop_crossbar) exposes the NUM_AGU-wide OBI agu[]
//   interface as flat packed SC ports (names include _i/_o Verilator suffixes):
//     agu_req_i    : sc_in  < uint32_t >               [NUM_AGU bits]
//     agu_addr_i   : sc_in  < sc_bv<NUM_AGU*32> >
//     agu_we_i     : sc_in  < uint32_t >               [NUM_AGU bits]
//     agu_be_i     : sc_in  < sc_bv<NUM_AGU*4> >
//     agu_wdata_i  : sc_in  < sc_bv<NUM_AGU*32> >
//     agu_gnt_o    : sc_out < uint32_t >               [NUM_AGU bits]
//     agu_rvalid_o : sc_out < uint32_t >               [NUM_AGU bits]
//     agu_rdata_o  : sc_out < sc_bv<NUM_AGU*32> >
//
//   This wrapper unpacks those into individual per-AGU sc_in/sc_out arrays
//   (m_req_i, m_addr_i, …) that match the native top_crossbar.hpp port names.
//   Two SC_METHODs (pack_inputs / unpack_outputs) keep the packed signals in
//   sync with the flat arrays combinatorially.
//
//   Template parameters correspond to the Verilator -G overrides:
//     NUM_AGU   ↔ GNum_AGU   (total manager ports = N_AGU * N_REQ, default 32)
//     NUM_BANKS ↔ GNum_Banks (number of memory banks, default 32)
//     BANK_ROWS ↔ GBank_Rows (rows per bank, default 1024)
//
//   NOTE: Verilated port names (agu_req, …) are generated by Verilator from the
//   interface member names in obi.sv.  If they differ on your Verilator
//   version, update the vdut.agu_* bindings in SC_CTOR below.
// -----------------------------------------------------------------------------

#ifndef TOP_CROSSBAR_SV_HPP
#define TOP_CROSSBAR_SV_HPP

#include <systemc.h>

#include <cstdint>

#include "Vtop_crossbar.h" // generated by Verilator --sc

template <int NUM_AGU = 32, int NUM_BANKS = 32, int BANK_ROWS = 1024>
SC_MODULE(top_crossbar_sv)
{
    // Clock and reset
    sc_in<bool> clk_i;
    sc_in<bool> rst_ni;

    // Manager-side ports: one OBI channel per manager port
    sc_in<bool>     m_req_i[NUM_AGU];
    sc_in<uint64_t> m_addr_i[NUM_AGU];   // upper 32 bits ignored; OBI is 32-bit
    sc_in<bool>     m_we_i[NUM_AGU];
    sc_in<uint32_t> m_be_i[NUM_AGU];
    sc_in<uint64_t> m_wdata_i[NUM_AGU];  // upper 32 bits ignored
    sc_out<bool>     m_gnt_o[NUM_AGU];
    sc_out<bool>     m_rvalid_o[NUM_AGU];
    sc_out<uint64_t> m_rdata_o[NUM_AGU]; // zero-extended from 32-bit OBI rdata

    // -----------------------------------------------------------------------
    // Verilated module instance
    // -----------------------------------------------------------------------
    Vtop_crossbar vdut;

    // -----------------------------------------------------------------------
    // Packed intermediate signals connecting to Verilated ports
    // Widths match the flattened OBI interface array in top_crossbar.sv:
    //   req/we/gnt/rvalid : NUM_AGU bits (one per port)
    //   addr/wdata/rdata  : NUM_AGU * 32 bits
    //   be                : NUM_AGU *  4 bits
    // -----------------------------------------------------------------------
    sc_signal<uint32_t> s_req;
    sc_signal<sc_bv<NUM_AGU * 32>> s_addr;
    sc_signal<uint32_t> s_we;
    sc_signal<sc_bv<NUM_AGU * 4>> s_be;
    sc_signal<sc_bv<NUM_AGU * 32>> s_wdata;
    sc_signal<uint32_t> s_gnt;
    sc_signal<uint32_t> s_rvalid;
    sc_signal<sc_bv<NUM_AGU * 32>> s_rdata;

    // Pack flat per-manager inputs → wide Verilated input signals
    void pack_inputs()
    {
        uint32_t req_v = 0;
        uint32_t we_v = 0;
        sc_bv<NUM_AGU * 32> addr_v;
        sc_bv<NUM_AGU * 4> be_v;
        sc_bv<NUM_AGU * 32> wdata_v;

        for (int i = 0; i < NUM_AGU; ++i)
        {
            if (m_req_i[i].read())
                req_v |= (1u << i);
            if (m_we_i[i].read())
                we_v |= (1u << i);
            addr_v.range(32 * (i + 1) - 1, 32 * i)  = static_cast<uint32_t>(m_addr_i[i].read());
            be_v.range(4 * (i + 1) - 1, 4 * i)      = m_be_i[i].read();
            wdata_v.range(32 * (i + 1) - 1, 32 * i) = static_cast<uint32_t>(m_wdata_i[i].read());
        }

        s_req.write(req_v);
        s_we.write(we_v);
        s_addr.write(addr_v);
        s_be.write(be_v);
        s_wdata.write(wdata_v);
    }

    // Unpack wide Verilated output signals → flat per-manager outputs
    void unpack_outputs()
    {
        const uint32_t gnt_v = s_gnt.read();
        const uint32_t rvalid_v = s_rvalid.read();
        const sc_bv<NUM_AGU * 32> rdata_v = s_rdata.read();

        for (int i = 0; i < NUM_AGU; ++i)
        {
            m_gnt_o[i].write((gnt_v >> i) & 1u);
            m_rvalid_o[i].write((rvalid_v >> i) & 1u);
            m_rdata_o[i].write(static_cast<uint64_t>(rdata_v.range(32 * (i + 1) - 1, 32 * i).to_uint()));
        }
    }

    SC_CTOR(top_crossbar_sv) : vdut("vdut")
    {
        // Clock / reset
        vdut.clk_i(clk_i);
        vdut.rst_ni(rst_ni);

        // Packed OBI manager port connections to Verilated module
        vdut.agu_req_i(s_req);
        vdut.agu_addr_i(s_addr);
        vdut.agu_we_i(s_we);
        vdut.agu_be_i(s_be);
        vdut.agu_wdata_i(s_wdata);
        vdut.agu_gnt_o(s_gnt);
        vdut.agu_rvalid_o(s_rvalid);
        vdut.agu_rdata_o(s_rdata);

        // Combinatorial pack: fire whenever any individual input changes
        SC_METHOD(pack_inputs);
        for (int i = 0; i < NUM_AGU; ++i)
            sensitive << m_req_i[i] << m_addr_i[i] << m_we_i[i]
                      << m_be_i[i] << m_wdata_i[i];

        // Combinatorial unpack: fire whenever any packed output changes
        SC_METHOD(unpack_outputs);
        sensitive << s_gnt << s_rvalid << s_rdata;
    }
};

#endif // TOP_CROSSBAR_SV_HPP
