// -----------------------------------------------------------------------------
// Author: Cedric Hölzl
//
// Description:
//   SystemC wrapper for the Verilated SV top_crossbar (Verilator --sc output).
//   Mirrors the port convention of the native rtl/systemc/top_crossbar.hpp so
//   that tb_top_crossbar.cpp can swap between the two DUTs by changing a single
//   #include and the class name.
//
//   The Verilated module (Vtop_crossbar) exposes both the read-AGU (agu_*)
//   and write-AGU (wagu_*) flat-packed SC ports:
//     agu_req_i     : sc_in  < uint32_t >           [NUM_MGR  bits]
//     agu_addr_i    : sc_in  < sc_bv<NUM_MGR*32>  >
//     agu_we_i      : sc_in  < uint32_t >           [NUM_MGR  bits]
//     agu_be_i      : sc_in  < sc_bv<NUM_MGR*4>   >
//     agu_wdata_i   : sc_in  < sc_bv<NUM_MGR*32>  >
//     agu_gnt_o     : sc_out < uint32_t >           [NUM_MGR  bits]
//     agu_rvalid_o  : sc_out < uint32_t >           [NUM_MGR  bits]
//     agu_rdata_o   : sc_out < sc_bv<NUM_MGR*32>  >
//     wagu_req_i    : sc_in  < uint32_t >           [NUM_WMGR bits]
//     wagu_addr_i   : sc_in  < sc_bv<NUM_WMGR*32> >
//     wagu_we_i     : sc_in  < uint32_t >           [NUM_WMGR bits]
//     wagu_be_i     : sc_in  < sc_bv<NUM_WMGR*4>  >
//     wagu_wdata_i  : sc_in  < sc_bv<NUM_WMGR*32> >
//     wagu_gnt_o    : sc_out < uint32_t >           [NUM_WMGR bits]
//     wagu_rvalid_o : sc_out < uint32_t >           [NUM_WMGR bits]
//     wagu_rdata_o  : sc_out < sc_bv<NUM_WMGR*32> >
//
//   This wrapper unpacks those into individual per-manager sc_in/sc_out arrays
//   (m_req_i / m_w_req_i, …) that match the native top_crossbar.hpp port names.
//   Four SC_METHODs (pack_inputs / unpack_outputs / pack_w_inputs /
//   unpack_w_outputs) keep the packed signals in sync with the flat arrays.
//
//   Template parameters correspond to the Verilator -G overrides:
//     N_AGU   ↔ -GN_AGU   (number of read AGUs,  default 7)
//     N_WAGU  ↔ -GN_WAGU  (number of write AGUs, default 6)
//     N_REQ   ↔ -GN_REQ   (request ports per AGU, default 4)
//     N_BANK  ↔ -GN_BANK  (number of memory banks, default 32)
//     N_ROW   ↔ -GN_ROW   (rows per bank, default 1024)
//
//   NOTE: Verilated port names (agu_req, wagu_req, …) are generated by
//   Verilator from the interface member names in obi.sv.  If they differ on
//   your Verilator version, update the vdut.agu_* / vdut.wagu_* bindings.
// -----------------------------------------------------------------------------

#ifndef TOP_CROSSBAR_SV_HPP
#define TOP_CROSSBAR_SV_HPP

#include <systemc.h>

#include <cstdint>

#include "Vtop_crossbar.h" // generated by Verilator --sc

template <int NUM_AGU = 7, int NUM_WAGU = 6, int NUM_REQ = 4, int NUM_BANK = 32, int NUM_ROW = 1024>
SC_MODULE(top_crossbar_sv)
{
    static constexpr int NUM_MGR = NUM_AGU * NUM_REQ;
    static constexpr int NUM_WMGR = NUM_WAGU * NUM_REQ;

    // Clock and reset
    sc_in<bool> clk_i;
    sc_in<bool> rst_ni;

    // Manager-side ports: one OBI channel per manager port
    sc_in<bool> m_req_i[NUM_MGR];
    sc_in<uint64_t> m_addr_i[NUM_MGR]; // upper 32 bits ignored; OBI is 32-bit
    sc_in<bool> m_we_i[NUM_MGR];
    sc_in<uint32_t> m_be_i[NUM_MGR];
    sc_in<uint64_t> m_wdata_i[NUM_MGR]; // upper 32 bits ignored
    sc_out<bool> m_gnt_o[NUM_MGR];
    sc_out<bool> m_rvalid_o[NUM_MGR];
    sc_out<uint64_t> m_rdata_o[NUM_MGR]; // zero-extended from 32-bit OBI rdata

    sc_in<bool> m_w_req_i[NUM_WMGR];
    sc_in<uint64_t> m_w_addr_i[NUM_WMGR]; // upper 32 bits ignored; OBI is 32-bit
    sc_in<bool> m_w_we_i[NUM_WMGR];
    sc_in<uint32_t> m_w_be_i[NUM_WMGR];
    sc_in<uint64_t> m_w_wdata_i[NUM_WMGR]; // upper 32 bits ignored
    sc_out<bool> m_w_gnt_o[NUM_WMGR];
    sc_out<bool> m_w_rvalid_o[NUM_WMGR];
    sc_out<uint64_t> m_w_rdata_o[NUM_WMGR]; // zero-extended from 32-bit OBI rdata

    // -----------------------------------------------------------------------
    // Verilated module instance
    // -----------------------------------------------------------------------
    Vtop_crossbar vdut;

    // -----------------------------------------------------------------------
    // Packed intermediate signals connecting to Verilated ports
    // Widths match the flattened OBI interface array in top_crossbar.sv:
    //   req/we/gnt/rvalid : NUM_MGR bits (one per port)
    //   addr/wdata/rdata  : NUM_MGR * 32 bits
    //   be                : NUM_MGR *  4 bits
    // -----------------------------------------------------------------------
    sc_signal<uint32_t> s_req;
    sc_signal<sc_bv<NUM_MGR * 32>> s_addr;
    sc_signal<uint32_t> s_we;
    sc_signal<sc_bv<NUM_MGR * 4>> s_be;
    sc_signal<sc_bv<NUM_MGR * 32>> s_wdata;
    sc_signal<uint32_t> s_gnt;
    sc_signal<uint32_t> s_rvalid;
    sc_signal<sc_bv<NUM_MGR * 32>> s_rdata;

    sc_signal<uint32_t> s_w_req;
    sc_signal<sc_bv<NUM_WMGR * 32>> s_w_addr;
    sc_signal<uint32_t> s_w_we;
    sc_signal<sc_bv<NUM_WMGR * 4>> s_w_be;
    sc_signal<sc_bv<NUM_WMGR * 32>> s_w_wdata;
    sc_signal<uint32_t> s_w_gnt;
    sc_signal<uint32_t> s_w_rvalid;
    sc_signal<sc_bv<NUM_WMGR * 32>> s_w_rdata;

    // Pack flat per-manager inputs → wide Verilated input signals
    void pack_inputs()
    {
        uint32_t req_v = 0;
        uint32_t we_v = 0;
        sc_bv<NUM_MGR * 32> addr_v;
        sc_bv<NUM_MGR * 4> be_v;
        sc_bv<NUM_MGR * 32> wdata_v;

        for (int i = 0; i < NUM_MGR; ++i)
        {
            if (m_req_i[i].read())
                req_v |= (1u << i);
            if (m_we_i[i].read())
                we_v |= (1u << i);
            addr_v.range(32 * (i + 1) - 1, 32 * i) = static_cast<uint32_t>(m_addr_i[i].read());
            be_v.range(4 * (i + 1) - 1, 4 * i) = m_be_i[i].read();
            wdata_v.range(32 * (i + 1) - 1, 32 * i) = static_cast<uint32_t>(m_wdata_i[i].read());
        }

        s_req.write(req_v);
        s_we.write(we_v);
        s_addr.write(addr_v);
        s_be.write(be_v);
        s_wdata.write(wdata_v);
    }

    // Unpack wide Verilated output signals → flat per-manager outputs
    void unpack_outputs()
    {
        const uint32_t gnt_v = s_gnt.read();
        const uint32_t rvalid_v = s_rvalid.read();
        const sc_bv<NUM_MGR * 32> rdata_v = s_rdata.read();

        for (int i = 0; i < NUM_MGR; ++i)
        {
            m_gnt_o[i].write((gnt_v >> i) & 1u);
            m_rvalid_o[i].write((rvalid_v >> i) & 1u);
            m_rdata_o[i].write(static_cast<uint64_t>(rdata_v.range(32 * (i + 1) - 1, 32 * i).to_uint()));
        }
    }

    // Pack flat per-write-manager inputs → wide Verilated wagu input signals
    void pack_w_inputs()
    {
        uint32_t req_v = 0;
        uint32_t we_v = 0;
        sc_bv<NUM_WMGR * 32> addr_v;
        sc_bv<NUM_WMGR * 4> be_v;
        sc_bv<NUM_WMGR * 32> wdata_v;

        for (int i = 0; i < NUM_WMGR; ++i)
        {
            if (m_w_req_i[i].read())
                req_v |= (1u << i);
            if (m_w_we_i[i].read())
                we_v |= (1u << i);
            addr_v.range(32 * (i + 1) - 1, 32 * i) = static_cast<uint32_t>(m_w_addr_i[i].read());
            be_v.range(4 * (i + 1) - 1, 4 * i) = m_w_be_i[i].read();
            wdata_v.range(32 * (i + 1) - 1, 32 * i) = static_cast<uint32_t>(m_w_wdata_i[i].read());
        }

        s_w_req.write(req_v);
        s_w_we.write(we_v);
        s_w_addr.write(addr_v);
        s_w_be.write(be_v);
        s_w_wdata.write(wdata_v);
    }

    // Unpack wide Verilated wagu output signals → flat per-write-manager outputs
    void unpack_w_outputs()
    {
        const uint32_t gnt_v = s_w_gnt.read();
        const uint32_t rvalid_v = s_w_rvalid.read();
        const sc_bv<NUM_WMGR * 32> rdata_v = s_w_rdata.read();

        for (int i = 0; i < NUM_WMGR; ++i)
        {
            m_w_gnt_o[i].write((gnt_v >> i) & 1u);
            m_w_rvalid_o[i].write((rvalid_v >> i) & 1u);
            m_w_rdata_o[i].write(static_cast<uint64_t>(rdata_v.range(32 * (i + 1) - 1, 32 * i).to_uint()));
        }
    }

    SC_CTOR(top_crossbar_sv) : vdut("vdut")
    {
        // Clock / reset
        vdut.clk_i(clk_i);
        vdut.rst_ni(rst_ni);

        // Packed OBI manager port connections to Verilated module
        vdut.agu_req_i(s_req);
        vdut.agu_addr_i(s_addr);
        vdut.agu_we_i(s_we);
        vdut.agu_be_i(s_be);
        vdut.agu_wdata_i(s_wdata);
        vdut.agu_gnt_o(s_gnt);
        vdut.agu_rvalid_o(s_rvalid);
        vdut.agu_rdata_o(s_rdata);

        vdut.wagu_req_i(s_w_req);
        vdut.wagu_addr_i(s_w_addr);
        vdut.wagu_we_i(s_w_we);
        vdut.wagu_be_i(s_w_be);
        vdut.wagu_wdata_i(s_w_wdata);
        vdut.wagu_gnt_o(s_w_gnt);
        vdut.wagu_rvalid_o(s_w_rvalid);
        vdut.wagu_rdata_o(s_w_rdata);

        // Combinatorial pack/unpack for read-AGU path
        SC_METHOD(pack_inputs);
        for (int i = 0; i < NUM_MGR; ++i)
            sensitive << m_req_i[i] << m_addr_i[i] << m_we_i[i]
                      << m_be_i[i] << m_wdata_i[i];

        SC_METHOD(unpack_outputs);
        sensitive << s_gnt << s_rvalid << s_rdata;

        // Combinatorial pack/unpack for write-AGU path
        SC_METHOD(pack_w_inputs);
        for (int i = 0; i < NUM_WMGR; ++i)
            sensitive << m_w_req_i[i] << m_w_addr_i[i] << m_w_we_i[i]
                      << m_w_be_i[i] << m_w_wdata_i[i];

        SC_METHOD(unpack_w_outputs);
        sensitive << s_w_gnt << s_w_rvalid << s_w_rdata;
    }
};

#endif // TOP_CROSSBAR_SV_HPP
